# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forbiddevdialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ForbidDevDialog(object):
    def setupUi(self, ForbidDevDialog):
        ForbidDevDialog.setObjectName("ForbidDevDialog")
        ForbidDevDialog.resize(593, 471)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ForbidDevDialog.sizePolicy().hasHeightForWidth())
        ForbidDevDialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(ForbidDevDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tipsLabel = QtWidgets.QLabel(ForbidDevDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tipsLabel.sizePolicy().hasHeightForWidth())
        self.tipsLabel.setSizePolicy(sizePolicy)
        self.tipsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tipsLabel.setObjectName("tipsLabel")
        self.verticalLayout.addWidget(self.tipsLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.previousPushButton = QtWidgets.QPushButton(ForbidDevDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.previousPushButton.sizePolicy().hasHeightForWidth())
        self.previousPushButton.setSizePolicy(sizePolicy)
        self.previousPushButton.setCheckable(True)
        self.previousPushButton.setAutoDefault(False)
        self.previousPushButton.setObjectName("previousPushButton")
        self.horizontalLayout.addWidget(self.previousPushButton)
        self.nextPushButton = QtWidgets.QPushButton(ForbidDevDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextPushButton.sizePolicy().hasHeightForWidth())
        self.nextPushButton.setSizePolicy(sizePolicy)
        self.nextPushButton.setCheckable(True)
        self.nextPushButton.setChecked(False)
        self.nextPushButton.setAutoDefault(False)
        self.nextPushButton.setObjectName("nextPushButton")
        self.horizontalLayout.addWidget(self.nextPushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(ForbidDevDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.forbidDevFrame = QtWidgets.QFrame(ForbidDevDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forbidDevFrame.sizePolicy().hasHeightForWidth())
        self.forbidDevFrame.setSizePolicy(sizePolicy)
        self.forbidDevFrame.setObjectName("forbidDevFrame")
        self.verticalLayout.addWidget(self.forbidDevFrame)
        self.forbidDevExitPushButton = QtWidgets.QPushButton(ForbidDevDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.forbidDevExitPushButton.sizePolicy().hasHeightForWidth())
        self.forbidDevExitPushButton.setSizePolicy(sizePolicy)
        self.forbidDevExitPushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.forbidDevExitPushButton.setDefault(True)
        self.forbidDevExitPushButton.setObjectName("forbidDevExitPushButton")
        self.verticalLayout.addWidget(self.forbidDevExitPushButton)

        self.retranslateUi(ForbidDevDialog)
        self.forbidDevExitPushButton.clicked.connect(ForbidDevDialog.close)
        QtCore.QMetaObject.connectSlotsByName(ForbidDevDialog)

    def retranslateUi(self, ForbidDevDialog):
        _translate = QtCore.QCoreApplication.translate
        ForbidDevDialog.setWindowTitle(_translate("ForbidDevDialog", "禁用设备列表"))
        self.tipsLabel.setText(_translate("ForbidDevDialog", "请点击禁用设备"))
        self.previousPushButton.setText(_translate("ForbidDevDialog", "上一页"))
        self.nextPushButton.setText(_translate("ForbidDevDialog", "下一页"))
        self.forbidDevExitPushButton.setText(_translate("ForbidDevDialog", "exit"))

