# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(854, 396)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(mainWindow)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.titleFrame = QtWidgets.QFrame(mainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleFrame.sizePolicy().hasHeightForWidth())
        self.titleFrame.setSizePolicy(sizePolicy)
        self.titleFrame.setMinimumSize(QtCore.QSize(0, 75))
        self.titleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleFrame.setObjectName("titleFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.titleFrame)
        self.horizontalLayout.setContentsMargins(150, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.versionLabel = QtWidgets.QLabel(self.titleFrame)
        self.versionLabel.setObjectName("versionLabel")
        self.horizontalLayout.addWidget(self.versionLabel)
        spacerItem = QtWidgets.QSpacerItem(540, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.internetLabel = QtWidgets.QLabel(self.titleFrame)
        self.internetLabel.setObjectName("internetLabel")
        self.horizontalLayout.addWidget(self.internetLabel)
        self.timeLabel = QtWidgets.QLabel(self.titleFrame)
        self.timeLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.timeLabel.setObjectName("timeLabel")
        self.horizontalLayout.addWidget(self.timeLabel)
        self.verticalLayout_3.addWidget(self.titleFrame)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.setting = QtWidgets.QGroupBox(mainWindow)
        self.setting.setTitle("")
        self.setting.setObjectName("setting")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.setting)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.settingTextLabel = QtWidgets.QLabel(self.setting)
        self.settingTextLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.settingTextLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.settingTextLabel.setObjectName("settingTextLabel")
        self.verticalLayout_2.addWidget(self.settingTextLabel)
        self.singleCtrlPushButton = QtWidgets.QPushButton(self.setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.singleCtrlPushButton.sizePolicy().hasHeightForWidth())
        self.singleCtrlPushButton.setSizePolicy(sizePolicy)
        self.singleCtrlPushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.singleCtrlPushButton.setIconSize(QtCore.QSize(16, 16))
        self.singleCtrlPushButton.setObjectName("singleCtrlPushButton")
        self.verticalLayout_2.addWidget(self.singleCtrlPushButton)
        self.settingDataPushButton = QtWidgets.QPushButton(self.setting)
        self.settingDataPushButton.setObjectName("settingDataPushButton")
        self.verticalLayout_2.addWidget(self.settingDataPushButton)
        self.userKeysPushButton = QtWidgets.QPushButton(self.setting)
        self.userKeysPushButton.setObjectName("userKeysPushButton")
        self.verticalLayout_2.addWidget(self.userKeysPushButton)
        self.forbidDevPushButton = QtWidgets.QPushButton(self.setting)
        self.forbidDevPushButton.setObjectName("forbidDevPushButton")
        self.verticalLayout_2.addWidget(self.forbidDevPushButton)
        self.settingDevPushButton = QtWidgets.QPushButton(self.setting)
        self.settingDevPushButton.setObjectName("settingDevPushButton")
        self.verticalLayout_2.addWidget(self.settingDevPushButton)
        self.accountPushButton = QtWidgets.QPushButton(self.setting)
        self.accountPushButton.setObjectName("accountPushButton")
        self.verticalLayout_2.addWidget(self.accountPushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.resetInverterPushButton = QtWidgets.QPushButton(self.setting)
        self.resetInverterPushButton.setObjectName("resetInverterPushButton")
        self.verticalLayout_4.addWidget(self.resetInverterPushButton)
        self.clearFaultPushButton = QtWidgets.QPushButton(self.setting)
        self.clearFaultPushButton.setObjectName("clearFaultPushButton")
        self.verticalLayout_4.addWidget(self.clearFaultPushButton)
        self.exitBushButton = QtWidgets.QPushButton(self.setting)
        self.exitBushButton.setObjectName("exitBushButton")
        self.verticalLayout_4.addWidget(self.exitBushButton)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3.addWidget(self.setting)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.contextFrame = QtWidgets.QFrame(mainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contextFrame.sizePolicy().hasHeightForWidth())
        self.contextFrame.setSizePolicy(sizePolicy)
        self.contextFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.contextFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contextFrame.setObjectName("contextFrame")
        self.verticalLayout.addWidget(self.contextFrame)
        self.analogControlGroupBox = QtWidgets.QGroupBox(mainWindow)
        self.analogControlGroupBox.setObjectName("analogControlGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.analogControlGroupBox)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.analogControlGroupBox)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.speedSetSlider = QtWidgets.QSlider(self.analogControlGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speedSetSlider.sizePolicy().hasHeightForWidth())
        self.speedSetSlider.setSizePolicy(sizePolicy)
        self.speedSetSlider.setMinimumSize(QtCore.QSize(300, 0))
        self.speedSetSlider.setMaximum(100)
        self.speedSetSlider.setOrientation(QtCore.Qt.Horizontal)
        self.speedSetSlider.setObjectName("speedSetSlider")
        self.gridLayout_2.addWidget(self.speedSetSlider, 1, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.analogControlGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Arial\";")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.analogControlGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdNumber.sizePolicy().hasHeightForWidth())
        self.lcdNumber.setSizePolicy(sizePolicy)
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.Panel)
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdNumber.setProperty("value", 0.0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout_2.addWidget(self.lcdNumber, 0, 1, 1, 2)
        self.horizontalLayout_2.addLayout(self.gridLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.raisePushButton = QtWidgets.QPushButton(self.analogControlGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.raisePushButton.sizePolicy().hasHeightForWidth())
        self.raisePushButton.setSizePolicy(sizePolicy)
        self.raisePushButton.setCheckable(True)
        self.raisePushButton.setObjectName("raisePushButton")
        self.horizontalLayout_2.addWidget(self.raisePushButton)
        self.stopPushButton = QtWidgets.QPushButton(self.analogControlGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopPushButton.sizePolicy().hasHeightForWidth())
        self.stopPushButton.setSizePolicy(sizePolicy)
        self.stopPushButton.setCheckable(True)
        self.stopPushButton.setObjectName("stopPushButton")
        self.horizontalLayout_2.addWidget(self.stopPushButton)
        self.dropPushButton = QtWidgets.QPushButton(self.analogControlGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dropPushButton.sizePolicy().hasHeightForWidth())
        self.dropPushButton.setSizePolicy(sizePolicy)
        self.dropPushButton.setCheckable(True)
        self.dropPushButton.setObjectName("dropPushButton")
        self.horizontalLayout_2.addWidget(self.dropPushButton)
        self.modelTextLabel = QtWidgets.QLabel(self.analogControlGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modelTextLabel.sizePolicy().hasHeightForWidth())
        self.modelTextLabel.setSizePolicy(sizePolicy)
        self.modelTextLabel.setMinimumSize(QtCore.QSize(0, 80))
        self.modelTextLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.modelTextLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.modelTextLabel.setObjectName("modelTextLabel")
        self.horizontalLayout_2.addWidget(self.modelTextLabel)
        self.verticalLayout.addWidget(self.analogControlGroupBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)

        self.retranslateUi(mainWindow)
        self.exitBushButton.clicked.connect(mainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Form"))
        self.versionLabel.setText(_translate("mainWindow", "v18.06.20"))
        self.internetLabel.setText(_translate("mainWindow", "网络已断开"))
        self.timeLabel.setText(_translate("mainWindow", "time"))
        self.settingTextLabel.setText(_translate("mainWindow", "设置"))
        self.singleCtrlPushButton.setText(_translate("mainWindow", "单控选择"))
        self.settingDataPushButton.setText(_translate("mainWindow", "设置数据"))
        self.userKeysPushButton.setText(_translate("mainWindow", "按键自定义"))
        self.forbidDevPushButton.setText(_translate("mainWindow", "禁用设置"))
        self.settingDevPushButton.setText(_translate("mainWindow", "设备设定"))
        self.accountPushButton.setText(_translate("mainWindow", "账号管理"))
        self.resetInverterPushButton.setText(_translate("mainWindow", "变频器复位"))
        self.clearFaultPushButton.setText(_translate("mainWindow", "清除故障"))
        self.exitBushButton.setText(_translate("mainWindow", "退出"))
        self.label_2.setText(_translate("mainWindow", "速度设置:"))
        self.label.setText(_translate("mainWindow", "速度(%):"))
        self.raisePushButton.setText(_translate("mainWindow", "上升"))
        self.stopPushButton.setText(_translate("mainWindow", "停止"))
        self.dropPushButton.setText(_translate("mainWindow", "下降"))
        self.modelTextLabel.setText(_translate("mainWindow", "单控模式"))

