# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingpara.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingPara(object):
    def setupUi(self, SettingPara):
        SettingPara.setObjectName("SettingPara")
        SettingPara.resize(210, 143)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingPara.sizePolicy().hasHeightForWidth())
        SettingPara.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(SettingPara)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.upperLimitPosLineEdit = QtWidgets.QLineEdit(SettingPara)
        self.upperLimitPosLineEdit.setObjectName("upperLimitPosLineEdit")
        self.gridLayout.addWidget(self.upperLimitPosLineEdit, 3, 1, 1, 2)
        self.devNameLabel = QtWidgets.QLabel(SettingPara)
        self.devNameLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.devNameLabel.setObjectName("devNameLabel")
        self.gridLayout.addWidget(self.devNameLabel, 0, 1, 1, 2)
        self.actualPosLabel = QtWidgets.QLabel(SettingPara)
        self.actualPosLabel.setObjectName("actualPosLabel")
        self.gridLayout.addWidget(self.actualPosLabel, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(SettingPara)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(SettingPara)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.targetPosLineEdit = QtWidgets.QLineEdit(SettingPara)
        self.targetPosLineEdit.setObjectName("targetPosLineEdit")
        self.gridLayout.addWidget(self.targetPosLineEdit, 2, 1, 1, 2)
        self.label = QtWidgets.QLabel(SettingPara)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(SettingPara)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.lowerLimitPosLineEdit = QtWidgets.QLineEdit(SettingPara)
        self.lowerLimitPosLineEdit.setObjectName("lowerLimitPosLineEdit")
        self.gridLayout.addWidget(self.lowerLimitPosLineEdit, 4, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(SettingPara)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(SettingPara)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.zeroPosLabel = QtWidgets.QLabel(SettingPara)
        self.zeroPosLabel.setObjectName("zeroPosLabel")
        self.gridLayout.addWidget(self.zeroPosLabel, 5, 1, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(SettingPara)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 6, 2, 1, 1)
        self.okPushButton = QtWidgets.QPushButton(SettingPara)
        self.okPushButton.setObjectName("okPushButton")
        self.gridLayout.addWidget(self.okPushButton, 6, 1, 1, 1)

        self.retranslateUi(SettingPara)
        QtCore.QMetaObject.connectSlotsByName(SettingPara)

    def retranslateUi(self, SettingPara):
        _translate = QtCore.QCoreApplication.translate
        SettingPara.setWindowTitle(_translate("SettingPara", "Form"))
        self.devNameLabel.setText(_translate("SettingPara", "TextLabel"))
        self.actualPosLabel.setText(_translate("SettingPara", "0"))
        self.label_6.setText(_translate("SettingPara", "设定位置："))
        self.label_4.setText(_translate("SettingPara", "软下限："))
        self.label.setText(_translate("SettingPara", "设备名称："))
        self.label_3.setText(_translate("SettingPara", "软上限："))
        self.label_2.setText(_translate("SettingPara", "当前位置："))
        self.label_5.setText(_translate("SettingPara", "零位："))
        self.zeroPosLabel.setText(_translate("SettingPara", "0"))
        self.cancelButton.setText(_translate("SettingPara", "Cancel"))
        self.okPushButton.setText(_translate("SettingPara", "Ok"))

