# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'singlectrlwidget.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SingleCtrlWidget(object):
    def setupUi(self, SingleCtrlWidget):
        SingleCtrlWidget.setObjectName("SingleCtrlWidget")
        SingleCtrlWidget.resize(629, 493)
        self.verticalLayout = QtWidgets.QVBoxLayout(SingleCtrlWidget)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.singleCtrlFrame = QtWidgets.QFrame(SingleCtrlWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.singleCtrlFrame.sizePolicy().hasHeightForWidth())
        self.singleCtrlFrame.setSizePolicy(sizePolicy)
        self.singleCtrlFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.singleCtrlFrame.setObjectName("singleCtrlFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.singleCtrlFrame)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.devGroupSelectFrame = QtWidgets.QFrame(self.singleCtrlFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.devGroupSelectFrame.sizePolicy().hasHeightForWidth())
        self.devGroupSelectFrame.setSizePolicy(sizePolicy)
        self.devGroupSelectFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.devGroupSelectFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.devGroupSelectFrame.setObjectName("devGroupSelectFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.devGroupSelectFrame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.subUpDevPushButton = QtWidgets.QPushButton(self.devGroupSelectFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subUpDevPushButton.sizePolicy().hasHeightForWidth())
        self.subUpDevPushButton.setSizePolicy(sizePolicy)
        self.subUpDevPushButton.setCheckable(True)
        self.subUpDevPushButton.setObjectName("subUpDevPushButton")
        self.horizontalLayout_2.addWidget(self.subUpDevPushButton)
        self.subDownDevPushButton = QtWidgets.QPushButton(self.devGroupSelectFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subDownDevPushButton.sizePolicy().hasHeightForWidth())
        self.subDownDevPushButton.setSizePolicy(sizePolicy)
        self.subDownDevPushButton.setCheckable(True)
        self.subDownDevPushButton.setObjectName("subDownDevPushButton")
        self.horizontalLayout_2.addWidget(self.subDownDevPushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.tipsLabel = QtWidgets.QLabel(self.devGroupSelectFrame)
        self.tipsLabel.setObjectName("tipsLabel")
        self.horizontalLayout_2.addWidget(self.tipsLabel)
        self.verticalLayout_2.addWidget(self.devGroupSelectFrame)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.subUpDevScrollArea = QtWidgets.QScrollArea(self.singleCtrlFrame)
        self.subUpDevScrollArea.setFrameShape(QtWidgets.QFrame.Box)
        self.subUpDevScrollArea.setWidgetResizable(True)
        self.subUpDevScrollArea.setObjectName("subUpDevScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 289, 396))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.subUpDevScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_4.addWidget(self.subUpDevScrollArea)
        self.subDownDevScrollArea = QtWidgets.QScrollArea(self.singleCtrlFrame)
        self.subDownDevScrollArea.setFrameShape(QtWidgets.QFrame.Box)
        self.subDownDevScrollArea.setWidgetResizable(True)
        self.subDownDevScrollArea.setObjectName("subDownDevScrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 288, 396))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.subDownDevScrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_4.addWidget(self.subDownDevScrollArea)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.singleCtrlFrame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(40)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.confirmPushButton = QtWidgets.QPushButton(SingleCtrlWidget)
        self.confirmPushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.confirmPushButton.setCheckable(True)
        self.confirmPushButton.setObjectName("confirmPushButton")
        self.horizontalLayout.addWidget(self.confirmPushButton)
        self.cancelPushButton = QtWidgets.QPushButton(SingleCtrlWidget)
        self.cancelPushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.cancelPushButton.setCheckable(True)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout.addWidget(self.cancelPushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(SingleCtrlWidget)
        QtCore.QMetaObject.connectSlotsByName(SingleCtrlWidget)

    def retranslateUi(self, SingleCtrlWidget):
        _translate = QtCore.QCoreApplication.translate
        SingleCtrlWidget.setWindowTitle(_translate("SingleCtrlWidget", "Form"))
        self.subUpDevPushButton.setText(_translate("SingleCtrlWidget", "台上设备"))
        self.subDownDevPushButton.setText(_translate("SingleCtrlWidget", "台下设备"))
        self.tipsLabel.setText(_translate("SingleCtrlWidget", "请选择设备"))
        self.confirmPushButton.setText(_translate("SingleCtrlWidget", "确认"))
        self.cancelPushButton.setText(_translate("SingleCtrlWidget", "全部取消"))

