# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'systemmanagementwidget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SystemManagementWidget(object):
    def setupUi(self, SystemManagementWidget):
        SystemManagementWidget.setObjectName("SystemManagementWidget")
        SystemManagementWidget.resize(478, 234)
        self.verticalLayout = QtWidgets.QVBoxLayout(SystemManagementWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(SystemManagementWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(SystemManagementWidget)
        self.frame.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_5.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.serverIpLineEdit = QtWidgets.QLineEdit(self.frame)
        self.serverIpLineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.serverIpLineEdit.setObjectName("serverIpLineEdit")
        self.gridLayout.addWidget(self.serverIpLineEdit, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_6.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_6.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_7.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_8.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.exitPushButton = QtWidgets.QPushButton(SystemManagementWidget)
        self.exitPushButton.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.exitPushButton.setAutoDefault(False)
        self.exitPushButton.setDefault(False)
        self.exitPushButton.setObjectName("exitPushButton")
        self.horizontalLayout.addWidget(self.exitPushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(SystemManagementWidget)
        self.exitPushButton.clicked.connect(SystemManagementWidget.close)
        QtCore.QMetaObject.connectSlotsByName(SystemManagementWidget)

    def retranslateUi(self, SystemManagementWidget):
        _translate = QtCore.QCoreApplication.translate
        SystemManagementWidget.setWindowTitle(_translate("SystemManagementWidget", "Form"))
        self.label.setText(_translate("SystemManagementWidget", "参数设置"))
        self.label_5.setText(_translate("SystemManagementWidget", "IP:"))
        self.label_4.setText(_translate("SystemManagementWidget", "Server IP:"))
        self.label_6.setText(_translate("SystemManagementWidget", "Netmask:"))
        self.label_7.setText(_translate("SystemManagementWidget", "Gateway:"))
        self.label_11.setText(_translate("SystemManagementWidget", "ID:"))
        self.exitPushButton.setText(_translate("SystemManagementWidget", "退出"))

